/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Liam",
  "url": "https://kuizuo.me",
  "baseUrl": "/",
  "favicon": "img/favicon.ico",
  "organizationName": "kuizuo",
  "projectName": "blog",
  "customFields": {
    "bio": "道阻且长，行则将至",
    "description": "是一个由Liam创建的个人博客，主要分享编程开发知识和项目，该网站基于 React 驱动的静态网站生成器 Docusaurus 构建。"
  },
  "themeConfig": {
    "image": "img/og.png",
    "metadata": [
      {
        "name": "author",
        "content": "Liam"
      },
      {
        "name": "keywords",
        "content": "blog, javascript, typescript, node, react, vue, web"
      },
      {
        "name": "keywords",
        "content": "编程爱好者, Web开发者, 写过爬虫, 学过逆向, 主攻ts全栈"
      }
    ],
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "logo": {
        "alt": "Liam",
        "src": "img/logo.webp",
        "srcDark": "img/logo.webp"
      },
      "hideOnScroll": true,
      "items": [
        {
          "label": "博客",
          "position": "right",
          "to": "blog"
        },
        {
          "label": "项目",
          "position": "right",
          "to": "project"
        },
        {
          "label": "关于",
          "position": "right",
          "to": "about"
        },
        {
          "label": "更多",
          "position": "right",
          "items": [
            {
              "label": "归档",
              "to": "blog/archive"
            },
            {
              "label": "留言箱",
              "to": "guestbook"
            }
          ]
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "学习",
          "items": [
            {
              "label": "博客",
              "to": "blog"
            },
            {
              "label": "归档",
              "to": "blog/archive"
            },
            {
              "label": "实战项目",
              "to": "project"
            },
            {
              "label": "前端示例",
              "to": "https://example.kuizuo.me"
            }
          ]
        },
        {
          "title": "社交媒体",
          "items": [
            {
              "label": "关于我",
              "to": "/about"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/kuizuo"
            },
            {
              "label": "Twitter",
              "href": "https://x.com/ku1zu0"
            },
            {
              "label": "掘金",
              "href": "https://juejin.cn/user/1565318510545901"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/M8cVcjDxkz"
            }
          ]
        },
        {
          "title": "网站",
          "items": [
            {
              "label": "js反混淆",
              "to": "https://js-deobfuscator.kuizuo.me"
            },
            {
              "label": "cyberChef",
              "to": "https://gchq.github.io/CyberChef"
            },
            {
              "label": "api服务",
              "to": "https://api.kuizuo.me"
            },
            {
              "label": "便民服务",
              "to": "https://service.kuizuo.me"
            },
            {
              "label": "站点监控",
              "to": "https://uptime.kuizuo.me"
            }
          ]
        },
        {
          "title": "更多",
          "items": [
            {
              "label": "友链",
              "position": "right",
              "to": "friends"
            },
            {
              "html": "\n                <a href=\"https://docusaurus.io\" target=\"_blank\" rel=\"noreferrer noopener\">\n                  <img src=\"/img/buildwith.png\" alt=\"build with docusaurus\" width=\"120\" height=\"50\"/>\n                </a>\n                "
            }
          ]
        }
      ],
      "copyright": "<p>Liam © 2025</p>"
    },
    "algolia": {
      "appId": "GV6YN1ODMO",
      "apiKey": "50303937b0e4630bec4a20a14e3b7872",
      "indexName": "kuizuo",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "prism": {
      "theme": {
        "plain": {
          "backgroundColor": "hsl(230, 1%, 98%)",
          "color": "hsl(230, 8%, 24%)"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "cdata"
            ],
            "style": {
              "color": "hsl(230, 4%, 64%)"
            }
          },
          {
            "types": [
              "doctype",
              "punctuation",
              "entity"
            ],
            "style": {
              "color": "hsl(230, 8%, 24%)"
            }
          },
          {
            "types": [
              "attr-name",
              "class-name",
              "boolean",
              "constant",
              "number",
              "atrule"
            ],
            "style": {
              "color": "hsl(35, 99%, 36%)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "hsl(301, 63%, 40%)"
            }
          },
          {
            "types": [
              "property",
              "tag",
              "symbol",
              "deleted",
              "important"
            ],
            "style": {
              "color": "hsl(5, 74%, 59%)"
            }
          },
          {
            "types": [
              "selector",
              "string",
              "char",
              "builtin",
              "inserted",
              "regex",
              "attr-value",
              "punctuation"
            ],
            "style": {
              "color": "hsl(119, 34%, 47%)"
            }
          },
          {
            "types": [
              "variable",
              "operator",
              "function"
            ],
            "style": {
              "color": "hsl(221, 87%, 60%)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "hsl(198, 99%, 37%)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "color": "hsl(230, 8%, 24%)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "hsl(220, 13%, 18%)",
          "color": "hsl(220, 14%, 71%)",
          "textShadow": "0 1px rgba(0, 0, 0, 0.3)"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "cdata"
            ],
            "style": {
              "color": "hsl(220, 10%, 40%)"
            }
          },
          {
            "types": [
              "doctype",
              "punctuation",
              "entity"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          },
          {
            "types": [
              "attr-name",
              "class-name",
              "maybe-class-name",
              "boolean",
              "constant",
              "number",
              "atrule"
            ],
            "style": {
              "color": "hsl(29, 54%, 61%)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "hsl(286, 60%, 67%)"
            }
          },
          {
            "types": [
              "property",
              "tag",
              "symbol",
              "deleted",
              "important"
            ],
            "style": {
              "color": "hsl(355, 65%, 65%)"
            }
          },
          {
            "types": [
              "selector",
              "string",
              "char",
              "builtin",
              "inserted",
              "regex",
              "attr-value"
            ],
            "style": {
              "color": "hsl(95, 38%, 62%)"
            }
          },
          {
            "types": [
              "variable",
              "operator",
              "function"
            ],
            "style": {
              "color": "hsl(207, 82%, 66%)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "hsl(187, 47%, 55%)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "java",
        "python",
        "php",
        "graphql",
        "rust",
        "toml",
        "protobuf",
        "diff"
      ],
      "defaultLanguage": "javascript",
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ]
    },
    "giscus": {
      "repo": "kuizuo/blog",
      "repoId": "MDEwOlJlcG9zaXRvcnkzOTc2MjU2MTI=",
      "category": "General",
      "categoryId": "DIC_kwDOF7NJDM4CPK95",
      "theme": "light",
      "darkTheme": "dark_dimmed"
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "liveCodeBlock": {
      "playgroundPosition": "top"
    },
    "zoom": {
      "selector": ".markdown :not(em) > img",
      "background": {
        "light": "rgb(255, 255, 255)",
        "dark": "rgb(50, 50, 50)"
      }
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs",
          "sidebarPath": "sidebars.ts",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": false,
        "theme": {
          "customCss": [
            "./src/css/custom.css",
            "./src/css/tweet-theme.css"
          ]
        },
        "sitemap": {
          "priority": 0.5
        },
        "gtag": {
          "trackingID": "G-S4SD5NXWXF",
          "anonymizeIP": true
        },
        "debug": true
      }
    ]
  ],
  "plugins": [
    "docusaurus-plugin-image-zoom",
    "@docusaurus/plugin-ideal-image",
    "@docusaurus/theme-mermaid",
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": true,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/img/logo.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "#12affa"
          }
        ]
      }
    ],
    [
      "vercel-analytics",
      {
        "debug": true,
        "mode": "auto"
      }
    ],
    [
      "./src/plugin/plugin-content-blog",
      {
        "path": "blog",
        "editLocalizedFiles": false,
        "blogDescription": "代码人生：编织技术与生活的博客之旅",
        "blogSidebarCount": 10,
        "blogSidebarTitle": "博文",
        "postsPerPage": 12,
        "showReadingTime": true,
        "feedOptions": {
          "type": "all",
          "title": "Liam",
          "description": "feedId:41215011978385457+userId:41840354283324416",
          "copyright": "Copyright © 2026 Liam Built with Docusaurus.<p><a href=\"http://beian.miit.gov.cn/\" class=\"footer_lin\">闽ICP备2020017848号-3</a></p>"
        }
      }
    ],
    null,
    null
  ],
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "Liam的个人博客"
      }
    }
  ],
  "stylesheets": [
    "https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Normal.min.css",
    "https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Medium.min.css",
    "https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Semibold.min.css",
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV",
      "crossorigin": "anonymous"
    }
  ],
  "i18n": {
    "defaultLocale": "zh-CN",
    "locales": [
      "zh-CN"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "onBrokenLinks": "warn",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "ssgWorkerThreads": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false
};
